version: '3'
services:
    node-application:
        container_name: "node-app"
        build: 
            dockerfile: Dockerfile
            context: ./node-app 
        volumes:
            - /app/node_modules 
            - ./node-app:/app
        ports:
          - 5000:5000
    nginx:
        container_name: "nginx"
        restart: always
        build: 
          dockerfile: Dockerfile
          context: ./react-app
        ports: 
          - 80:80
          - 443:443
    database:
        image: "postgres"
        container_name: "psql"
        env_file:
          - ./node-app/.env
        volumes:
          - database-data:/var/lib/postgresql/data/
volumes:
  database-data: